Practice using PyTorch tensors

In [32]:
#create some tensors and vectors
import torch
import numpy as np

v = torch.tensor([1, 2, 3])

A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
B = torch.tensor([[1,2],[3,4],[5,6]])

In [33]:
#practice matrix multiplication, reshaping etc.

C = A.matmul(v)
print(C)

D = A.matmul(B)
print(D)

print(B.reshape(2,3))

print(B.reshape(2,3).matmul(A))


tensor([14, 32, 50])
tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[30, 36, 42],
        [66, 81, 96]])


In [34]:
#tensor properties
print(B.shape)
print(B.dtype)
print(B.device)

torch.Size([3, 2])
torch.int64
cpu


In [36]:
#converting between numpy arrays
arr = np.array([1, 2, 3])
t = torch.from_numpy(arr)

print(t)


tensor([1, 2, 3])


In [38]:
arr_from_tensor = B.numpy()
print(arr_from_tensor)

[[1 2]
 [3 4]
 [5 6]]


Tensor notation example:
$$X \in \mathbb{R}^{m \times n}$$

Example loss function: MSE

$$L=\frac{1}{N}\sum_{i=1}^{N}(y_i-\hat{y}_i)^2$$